Kubit.Core.Cliente/Pages/Custom/KitchenDisplay.cshtml.cs
using Kubit.Core.Cliente.Handlers;
using Kubit.Core.Cliente.Services.Consulta;
using Kubit.Core.Cliente.Services.Sistema;
using Kubit.Core.Modelo.Schemas.Consulta;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Kubit.Core.Cliente.Pages.Custom
{
    public class KitchenDisplayModel : PageModel
    {
        [BindProperty] public string ProgramaUuid { get; set; } = string.Empty;
        [BindProperty] public string Directorio { get; set; } = string.Empty;
        public Fn_ParamConsulta_Vista_Json Fn_ParamConsulta_Vista_Json { get; private set; } = new();
        public string Table { get; set; } = string.Empty;

        private readonly IProgramaService programaService;
        private readonly IParamConsultaService paramConsultaService;
        private readonly ConsultaHandler consultaHandler;

        public KitchenDisplayModel(IProgramaService programaService, IParamConsultaService pParamConsultaService, ConsultaHandler pConsultaHandler)
        {
            this.programaService = programaService;
            this.paramConsultaService = pParamConsultaService;
            this.consultaHandler = pConsultaHandler;
        }
        public async Task OnGetAsync()
        {
            this.SetSessionProgramaUuid();
            await this.SetSessionProgramaTablaPrimaria();

            var vistaJson = await this.consultaHandler.GetVistaJsonAsync(this.ProgramaUuid);

            if (vistaJson != null)
            {
                this.Fn_ParamConsulta_Vista_Json = vistaJson;
            }

            this.HttpContext.Session.SetString("Directorio", this.Directorio);
        }

        private void SetSessionProgramaUuid()
        {
            if (!string.IsNullOrEmpty(this.ProgramaUuid))
            {
                this.HttpContext.Session.SetString("ProgramaUuid", this.ProgramaUuid);
            }
            else
            {
                this.ProgramaUuid = this.HttpContext.Session.GetString("ProgramaUuid") ?? string.Empty;
            }
        }

        private async Task SetSessionProgramaTablaPrimaria()
        {
            var programa = await programaService.GetProgramaUuidAsync(ProgramaUuid);

            if (programa != null && !string.IsNullOrEmpty(programa.ProgramaTablaPrimaria))
            {
                this.HttpContext.Session.SetString("ProgramaTablaPrimaria", programa.ProgramaTablaPrimaria);
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            this.SetSessionProgramaUuid();
            await this.SetSessionProgramaTablaPrimaria();

            var vistaJson = await this.consultaHandler.GetVistaJsonAsync(this.ProgramaUuid);

            if (vistaJson != null)
            {
                this.Fn_ParamConsulta_Vista_Json = vistaJson;
            }

            this.HttpContext.Session.SetString("Directorio", this.Directorio);

            return this.Page();
        }

        public IActionResult OnPostRedirectToForm()
        {
            this.HttpContext.Session.SetString("Accion", "A");

            var directorioActual = this.HttpContext.Session.GetString("Directorio") ?? string.Empty;
            var nuevoDirectorio = string.IsNullOrEmpty(directorioActual)
                ? "Agregar"
                : $"{directorioActual} / Agregar";

            this.HttpContext.Session.SetString("Directorio", nuevoDirectorio);

            return this.RedirectToPage("../MainForm");
        }
    }
}

Kubit.Core.Cliente/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Kubit.Core.Cliente.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Kubit.Core.Cliente/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Kubit.Core.Cliente.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Kubit.Core.Cliente/Pages/MainForm.cshtml.cs
using Kubit.Core.Cliente.Handlers;
using Kubit.Core.Cliente.Services.Ejecucion;
using Kubit.Core.Cliente.Services.Sistema;
using Kubit.Core.Modelo.Response;
using Kubit.Core.Modelo.Templates;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Kubit.Core.Cliente.Pages
{
    public class MainFormModel : PageModel
    {
        public required string Directorio { get; set; }
        public Modelo.Templates.Modelo Modelo { get; set; } = new();
        [BindProperty] public Valores Valores { get; set; } = new();
        [BindProperty] public List<SubValores> SubValores { get; set; } = new();

        private readonly IFormJsonService formJsonService;
        private readonly IEjecucionService ejecucionService;
        private readonly ConsultaHandler consultaHandler;
        private readonly SqlHandler sqlHandler;

        public MainFormModel(IFormJsonService pFormJsonService, IEjecucionService pEjecucionService, ConsultaHandler pConsultaHandler, SqlHandler pSqlHandler)
        {
            this.formJsonService = pFormJsonService;
            this.ejecucionService = pEjecucionService;
            this.consultaHandler = pConsultaHandler;
            this.sqlHandler = pSqlHandler;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var httpContext = this.HttpContext;

            if (httpContext == null)
            {
                return StatusCode(500, "HttpContext no disponible");
            }

            this.Directorio = httpContext.Session.GetString("Directorio") ?? string.Empty;

            string empresaUuid = httpContext.Session.GetString("EmpresaUuid") ?? string.Empty;
            string programaUuid = httpContext.Session.GetString("ProgramaUuid") ?? string.Empty;
            string programaTablaPrimaria = httpContext.Session.GetString("ProgramaTablaPrimaria") ?? string.Empty;

            if (string.IsNullOrWhiteSpace(programaUuid) || string.IsNullOrWhiteSpace(programaTablaPrimaria))
            {
                return Page();
            }

            string accion = this.HttpContext.Session.GetString("Accion") ?? string.Empty;

            // Ya no es string, sino TablaModelo
            var modelo = await this.formJsonService.GetTemplateAsync(programaTablaPrimaria, empresaUuid, accion);

            if (modelo == null)
            {
                return Page();
            }

            this.Modelo = modelo;

            return Page();
        }

        public async Task<IActionResult> OnGetConsultaDatosAsync(string pParamConsultaUuid, string pParamParents)
        {
            var httpContext = this.HttpContext;

            if (httpContext == null)
            {
                return StatusCode(500, "HttpContext no disponible");
            }

            try
            {
                string programaUuid = httpContext.Session.GetString("ProgramaUuid") ?? string.Empty;

                var resultado = await this.consultaHandler.GetDatosJsonAsync(pParamConsultaUuid, programaUuid);

                return new JsonResult(resultado);
            }
            catch (Exception)
            {
                return new JsonResult(new
                {
                    success = false,
                    message = "Error al obtener datos de búsqueda."
                })
                { StatusCode = 500 };
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            try
            {
                string sqlModeloBuild = this.sqlHandler.BuildSqlModel(1, this.Valores);

                string sqlSubModelBuild = this.sqlHandler.BuildSqlSubModel(this.SubValores);

                if (string.IsNullOrEmpty(sqlModeloBuild))
                {
                    return Page();
                }

                string sqlTotal = string.Join(Environment.NewLine, sqlModeloBuild, sqlSubModelBuild);

                var response = await this.ejecucionService.EjecutarNonQueryAsync(sqlTotal);

                return new JsonResult(new
                {
                    success = response.Success,
                    message = response.Success ? "Registro guardado exitosamente" : response.Message
                });
            }
            catch (Exception ex)
            {
                return new JsonResult(new
                {
                    success = false,
                    message = "Error inesperado",
                    detalle = ex.Message
                });
            }
        }

        public IActionResult OnPostRedirectToGridAsync()
        {
            var directorioActual = HttpContext.Session.GetString("Directorio") ?? string.Empty;

            // Quitar " / Agregar" al final si existe
            var nuevoDirectorio = directorioActual.EndsWith(" / Agregar")
                ? directorioActual.Substring(0, directorioActual.Length - " / Agregar".Length)
                : directorioActual;

            HttpContext.Session.SetString("Directorio", nuevoDirectorio);

            return RedirectToPage("MainGrid");
        }
    }
}

Kubit.Core.Cliente/Pages/Index.cshtml
@page "/Index"

@model Kubit.Core.Cliente.Pages.IndexModel
@{
}

Kubit.Core.Cliente/Pages/MainForm.cshtml
@page "/MainForm"
@using Kubit.Core.Modelo.Templates
@using System.Text.Json
@model Kubit.Core.Cliente.Pages.MainFormModel

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item fw-bold">@this.Model.Directorio</li>
    </ol>
</nav>

<br />

<form id="mainForm" method="post" class="needs-validation" novalidate>
    @{
        int index = 0;
    }

    @foreach (var modelo in this.Model.Modelo.Campos)
    {
        var field = modelo;
        
        if (field.Value.Control != "submodel")
        {
            @await Html.PartialAsync("_Modelo", modelo)
        }

        else if (field.Value.Control == "submodel")
        {
            @if (field.Value.SubModelos != null)
            {
                foreach (var subModel in field.Value.SubModelos)
                {
                    var tabla = subModel.Tabla;
                    var header = field.Value.Label;
                    var hidden = field.Value.Hidden ?? false;

                    <div class="form-group mb-3 needs-validation @(hidden ? "d-none" : "")" novalidate id="SubValores_@tabla">
                        <div class="card mb-3">
                            <div class="card-header fw-bold">
                                @header
                            </div>
                            <div class="card-body">
                                @await Html.PartialAsync("_SubModelo", subModel)
                            </div>
                        </div>

                        <input type="hidden" id="hddSubValoresT_@tabla" name="SubValores[@index].Tabla" />
                        <input type="hidden" id="hddSubValoresD_@tabla" name="SubValores[@index].Datos" />

                        <div id="render_@tabla"></div>
                    </div>

                    index++;
                }
            }
        }
    }

    <input type="hidden" name="Valores.Tabla" value="@this.Model.Modelo.Tabla" />

    <br />

    @if (this.Model.Modelo.Campos?.Any() == true)
    {
        <div class="modal-footer d-grid gap-2 d-md-flex justify-content-md-end">
            <button class="btn btn-light me-md-2" type="submit" onclick="submitForm(event)">Guardar</button>
            <button class="btn btn-light" type="submit" onclick="submitRedirectToGrid('RedirectToGrid')">Salir</button>
        </div>
    }
    else
    {
        <p class='text-center'>La plantilla no está disponible. Contacte a su administrador</p>
        <div class="modal-footer d-grid gap-2 d-md-flex justify-content-md-end">
            <button class="btn btn-light" type="button" onclick="submitRedirectToGrid('RedirectToGrid')">Salir</button>
        </div>
    }
</form>

Kubit.Core.Cliente/Pages/MainGrid.cshtml
@page "/MainGrid"
@using System.Text.Json

@model Kubit.Core.Cliente.Pages.MainGridModel

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item fw-bold">@this.Model.Directorio</li>
    </ol>
</nav>

<div class="d-flex justify-content-between align-items-center mb-3">
    <div class="btn-group ms-auto" role="group" aria-label="Button group with nested dropdown">
        <form method="post">
            <button type="submit" asp-page-handler="RedirectToForm" class="btn btn-light d-flex align-items-center gap-2">
                <span class="material-symbols-outlined fs-5">new_window</span>
                <span>Agregar</span>
            </button>
        </form>
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <span>Exportar</span>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Excel</a></li>
                <li><a class="dropdown-item" href="#">PDF</a></li>
            </ul>
        </div>
    </div>
</div>

<br />
<div id="tabla-container"></div>

@{
    var gridJson = Model.Fn_ParamConsulta_Vista_Json;
    var columnas = gridJson?.Columnas;
    var datos = gridJson?.Datos;

    bool columnasValidas = columnas.HasValue && columnas.Value.ValueKind != JsonValueKind.Undefined;
    bool datosValidos = datos.HasValue && datos.Value.ValueKind != JsonValueKind.Undefined;
}

@if (columnasValidas)
{
    var columnasJson = JsonSerializer.Serialize(columnas);
    var datosJson = JsonSerializer.Serialize(datos);

    <script type="text/javascript">
        require(['functionGrid'], function(grid) {
            const columnas = @Html.Raw(columnasJson);
            const datos = @Html.Raw(datosJson);

            console.log("Columnas:", columnas);
            grid.createView('tabla-container', columnas, datos);
        });
    </script>
}